import type { RestCountry } from "@/types";

const populationFormatter = new Intl.NumberFormat("en", {
  maximumFractionDigits: 0
});

const INDEPENDENCE_DAY_BY_CCA2: Record<string, string> = {
  AF: "August 19",
  AL: "November 28",
  DZ: "July 5",
  AO: "November 11",
  AG: "November 1",
  AR: "July 9",
  AM: "September 21",
  AU: "January 26",
  AT: "October 26",
  AZ: "October 18",
  BS: "July 10",
  BH: "December 16",
  BD: "March 26",
  BB: "November 30",
  BY: "July 3",
  BE: "July 21",
  BZ: "September 21",
  BJ: "August 1",
  BT: "December 17",
  BO: "August 6",
  BA: "March 1",
  BW: "September 30",
  BR: "September 7",
  BG: "March 3",
  BF: "August 5",
  BI: "July 1",
  KH: "November 9",
  CM: "May 20",
  CA: "July 1",
  CV: "July 5",
  CF: "August 13",
  TD: "August 11",
  CL: "September 18",
  CN: "October 1 (National Day)",
  CO: "July 20",
  KM: "July 6",
  CG: "August 15",
  CD: "June 30",
  CR: "September 15",
  CI: "August 7",
  HR: "May 30",
  CU: "May 20",
  CY: "October 1",
  CZ: "October 28",
  DK: "June 5 (Constitution Day)",
  DJ: "June 27",
  DM: "November 3",
  DO: "February 27",
  EC: "August 10",
  EG: "July 23",
  SV: "September 15",
  GQ: "October 12",
  ER: "May 24",
  EE: "February 24",
  SZ: "September 6",
  ET: "May 28 (National Day)",
  FJ: "October 10",
  FI: "December 6",
  FR: "July 14",
  GA: "August 17",
  GM: "February 18",
  GE: "May 26",
  DE: "October 3",
  GH: "March 6",
  GR: "March 25",
  GD: "February 7",
  GT: "September 15",
  GN: "October 2",
  GW: "September 24",
  GY: "May 26",
  HT: "January 1",
  HN: "September 15",
  HU: "August 20 (National Day)",
  IS: "June 17",
  IN: "August 15",
  ID: "August 17",
  IQ: "October 3",
  IE: "April 24",
  IL: "May 14",
  IT: "June 2",
  JM: "August 6",
  JP: "February 11 (National Foundation Day)",
  JO: "May 25",
  KZ: "December 16",
  KE: "December 12",
  KI: "July 12",
  KW: "February 25",
  KG: "August 31",
  LA: "December 2",
  LV: "November 18",
  LB: "November 22",
  LS: "October 4",
  LR: "July 26",
  LY: "December 24",
  LT: "February 16",
  LU: "June 23 (National Day)",
  MG: "June 26",
  MW: "July 6",
  MY: "August 31",
  MV: "July 26",
  ML: "September 22",
  MT: "September 21",
  MH: "May 1",
  MR: "November 28",
  MU: "March 12",
  MX: "September 16",
  FM: "November 3",
  MD: "August 27",
  MN: "December 29",
  ME: "May 21",
  MA: "November 18",
  MZ: "June 25",
  MM: "January 4",
  NA: "March 21",
  NR: "January 31",
  NP: "September 20 (Constitution Day)",
  NL: "July 26 (Act of Abjuration)",
  NZ: "February 6 (Waitangi Day)",
  NI: "September 15",
  NE: "August 3",
  NG: "October 1",
  MK: "September 8",
  NO: "May 17",
  OM: "November 18",
  PK: "August 14",
  PW: "October 1",
  PA: "November 3",
  PG: "September 16",
  PY: "May 14",
  PE: "July 28",
  PH: "June 12",
  PL: "November 11",
  PT: "December 1",
  QA: "December 18",
  RO: "December 1",
  RW: "July 1",
  KN: "September 19",
  LC: "February 22",
  VC: "October 27",
  WS: "June 1",
  ST: "July 12",
  SA: "September 23",
  SN: "April 4",
  RS: "February 15",
  SC: "June 29",
  SL: "April 27",
  SG: "August 9",
  SK: "January 1",
  SI: "June 25",
  SB: "July 7",
  SO: "July 1",
  ZA: "April 27",
  KR: "August 15",
  SS: "July 9",
  ES: "October 12 (National Day)",
  LK: "February 4",
  SD: "January 1",
  SR: "November 25",
  SE: "June 6",
  CH: "August 1",
  SY: "April 17",
  TJ: "September 9",
  TZ: "December 9",
  TH: "December 5 (National Day)",
  TL: "May 20",
  TG: "April 27",
  TO: "June 4",
  TT: "August 31",
  TN: "March 20",
  TR: "October 29",
  TM: "September 27",
  TV: "October 1",
  UG: "October 9",
  UA: "August 24",
  AE: "December 2",
  GB: "June 14 (King's Official Birthday)",
  US: "July 4",
  UY: "August 25",
  UZ: "September 1",
  VU: "July 30",
  VE: "July 5",
  VN: "September 2",
  YE: "November 30",
  ZM: "October 24",
  ZW: "April 18"
};

export function formatPopulation(population: number | undefined): string {
  if (typeof population !== "number") {
    return "Not listed";
  }

  return populationFormatter.format(population);
}

export function getIndependenceDay(country: RestCountry): string {
  const knownDay = INDEPENDENCE_DAY_BY_CCA2[country.cca2];

  if (knownDay) {
    return knownDay;
  }

  if (country.independent === false) {
    return "Not applicable";
  }

  return "Not listed";
}
